### ISSUE TITLE
installation fails  in recent RedHat/Fedora environments

### ISSUE THREAD

**Issue by frans-fuerst** [albertz/music-player-core#9] opened 2015-05-09 17:36 UTC
On Fedora 21 `pip install musicplayer` fails with a compile error due to wrong include path:

```
PlayerInStream.hpp:9:34: fatal error: libavformat/avformat.h: No such file or directory
```

The desired files are installed via the `ffmpeg-devel` package but they are located under `/usr/include/ffmpeg/libavformat/`

As reported for other projects this seems to be not a bug in the package but a change in the ffmpeg-project, see here:
- https://github.com/dirkvdb/ffmpegthumbnailer/issues/18
- https://ask.fedoraproject.org/en/question/31642/how-to-install-libav-devel-packages-properly

I didn't try it but simply adding `/usr/include/ffmpeg` to the include paths might (quick)fix this.

**Comment by hamiljf** [comment] 2016-01-05 10:20
I suspect I have a somewhat similar problem using Ubuntu 14.04 LTS ...
after trying the following I gave up in confusion.

**sudo easy_install musicplayer**
Searching for musicplayer
Reading https://pypi.python.org/simple/musicplayer/
Best match: musicplayer 1.20141030.091600
Downloading https://pypi.python.org/packages/source/m/musicplayer/musicplayer-1.20141030.091600.tar.gz#md5=489e2cf4dc28bc35bda13f9c9b38e984
Processing musicplayer-1.20141030.091600.tar.gz
Writing /tmp/easy_install-Hct1wr/musicplayer-1.20141030.091600/setup.cfg
Running musicplayer-1.20141030.091600/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Hct1wr/musicplayer-1.20141030.091600/egg-dist-tmp-kwGItz
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from musicplayer.h:38:0,
                 from musicplayer_getmetadata.cpp:9:
PyThreading.hpp:7:33: fatal error: boost/noncopyable.hpp: No such file or directory
 #include <boost/noncopyable.hpp>
                                 ^
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1


**sudo apt-get install python-dev libsnappy-dev libtool yasm libchromaprint-dev portaudio19-dev libboost-dev**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-dev is already the newest version.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 portaudio19-dev : Depends: libjack-dev
E: Unable to correct problems, you have held broken packages.


**sudo apt-get install libjack-dev**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 libjack-dev : Depends: libjack0 (= 1:0.121.3+20120418git75e3e20b-2.1ubuntu1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by fredericgermain** [comment] 2016-05-10 09:03
I made a fix for fedora 23 : https://github.com/albertz/music-player-core/pull/10

dnf install ffmpeg-devel portaudio-devel libchromaprint-devel

**Comment by albertz** [comment] 2018-10-18 19:21
It sounds like this is fixed. Closing now. Please reopen if the problem is still there, or open another issue if there is another problem.

**Closed by albertz** 2018-10-18 19:21 UTC
